// Generated by npm run import:assets. Do not edit. Only QA-passed frames are included.
import type { ItemCatalog } from "./types.ts";
export const GENERATED_ITEMS = {
  "mint-shirt": {
    slot: "top",
    label: "민트 티셔츠",
    setId: "set-001",
    poses: {
      basic: {
        cream: {
          layers: [
            {
              src: "/hamsters/wardrobe/set-001/top/basic-cream.png",
              x: 0,
              y: 0,
              width: 1000,
              height: 1000,
              zIndex: 20,
            },
          ],
          qa: {
            status: "passed",
            reviewer: "user-approved + art-lead",
            reviewedAt: "2026-09-30T16:32:00Z",
          },
        },
        gray: {
          layers: [
            {
              src: "/hamsters/wardrobe/set-001/top/basic-gray.png",
              x: 0,
              y: 0,
              width: 1000,
              height: 1000,
              zIndex: 20,
            },
          ],
          qa: {
            status: "passed",
            reviewer: "user-approved + art-lead",
            reviewedAt: "2026-09-30T16:32:00Z",
          },
        },
      },
    },
  },
} as const satisfies ItemCatalog;
