// Required schema columns from the existing readiness contract.
// These are fixed identifiers, never user input.
export const readinessSchema = [
  { table: 'users', columns: ['id', 'email', 'updated_at'] },
  { table: 'auth_sessions', columns: ['id'] },
  { table: 'auth_refresh_tokens', columns: ['created_at'] },
  { table: 'auth_rate_limits', columns: ['attempts'] },
  { table: 'measurement_create_requests', columns: ['key'] },
  { table: 'avatar_products', columns: ['catalog_revision'] },
  { table: 'avatar_outfits', columns: ['revision'] },
  { table: 'avatar_ownerships', columns: ['source'] },
  { table: 'avatar_purchases', columns: ['price'] },
  { table: 'currency_transactions', columns: ['amount'] },
  { table: 'user_currencies', columns: ['balance'] },
  {
    table: 'user_preferences',
    columns: ['exercise_volume', 'exercise_goal', 'owned_tools', 'updated_at'],
  },
  { table: 'workout_curricula', columns: ['id'] },
  { table: 'user_curriculum_assignments', columns: ['id'] },
  { table: 'workout_routines', columns: ['id'] },
  { table: 'workout_routine_items', columns: ['id'] },
  { table: 'workout_routine_requests', columns: ['key'] },
  { table: 'workout_routine_events', columns: ['key'] },
  { table: 'groups', columns: ['id'] },
  { table: 'group_memberships', columns: ['group_id'] },
  { table: 'group_join_requests', columns: ['id'] },
  { table: 'group_create_requests', columns: ['key'] },
  { table: 'group_notifications', columns: ['id'] },
  { table: 'group_mission_rounds', columns: ['id'] },
  { table: 'activity_achievements', columns: ['id'] },
  { table: 'group_roulette_tickets', columns: ['id'] },
  { table: 'group_roulette_draws', columns: ['id'] },
  { table: 'streak_roulette_policies', columns: ['version'] },
  { table: 'streak_roulette_tickets', columns: ['id'] },
  { table: 'streak_roulette_draws', columns: ['id'] },
  { table: 'routine_activity_rewards', columns: ['routine_id'] },
] as const;
